apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2025-05-30T04:12:50Z"
  generation: 8
  labels:
    app: spring-petclinic-rest-recreate
  name: spring-petclinic-rest-recreate
  namespace: default
  resourceVersion: "2246"
  uid: 97035214-37c3-416d-8096-af010df6686f
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-rest-recreate
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-rest-recreate
    spec:
      containers:
      - image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
        imagePullPolicy: IfNotPresent
        name: spring-petclinic-rest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-05-30T04:12:50Z"
    lastUpdateTime: "2025-05-30T04:14:47Z"
    message: ReplicaSet "spring-petclinic-rest-recreate-5d9f8995f5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-30T04:22:57Z"
    lastUpdateTime: "2025-05-30T04:22:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
