apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T04:12:59Z"
  labels:
    app: spring-petclinic-rest-recreate
  name: spring-petclinic-rest-recreate
  namespace: default
  resourceVersion: "1302"
  uid: 61c49051-3398-43f6-9686-6ed68b735cc8
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.210.61
  clusterIPs:
  - 10.110.210.61
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32040
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest-recreate
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
