apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T18:51:26Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2951"
  uid: 2666a310-4f3c-49a5-848f-321c9a17619a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.62.234
  clusterIPs:
  - 10.101.62.234
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30798
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
